version: '3.8'

services:
  luaw:
    build: .
    container_name: luaw
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: mydatabase
    volumes:
      - .:/app
    ports:
      - "9000:8080"
    command: ["lua5.3", "luaw.lua"]
    entrypoint: []
    networks:
      - app-network

  luaw-tests:
    build: .
    container_name: luaw-tests
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: mydatabase
    volumes:
      - .:/app
    command: ["busted", "tests/", "--pattern=.lua"]
    entrypoint: []
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "9090:80"
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
